### ISSUE TITLE
Model architecture evaluated in the paper

### ISSUE THREAD

**Issue by chenzongxiong** [AmanPriyanshu/DP-HyperparamTuning#3]
I checked your source code closely and found there is a toy model given in your demo. 

I want to reproduce your paper's results. Can you share me the  model and search space you used to evaluate in the paper?
It would be very nice if you can provide the script used in the paper directly. 

Thanks.

**Comment by AmanPriyanshu** [comment]
Search Space for replication: `LR = [0.001, 0.1], NM = [0.5, 3]` and System Used: `Tesla P100 16GB - GPU & 13GB RAM Intel Xeon - CPU`. Models will be refined and uploaded for reproduction. In the mean time, I've sent the version we've used directly to you.
